### ISSUE TITLE
The .scss | .sass module could not be found.

### ISSUE THREAD

**Issue by wesleyamaro** [kristerkari/react-native-css-modules#13] opened 2018-08-16 14:43 UTC
11:29:49 AM: Unable to resolve ./index.scss" from ".//src/containers/Login/index.js`: The module `./index.scss` could not be found"
11:29:49 AM: Failed building JavaScript bundle
11:29:49 AM: Unable to resolve ./index.scss" from ".//src/containers/Login/index.js`: The module `./index.scss` could not be found"

**react native version**
`react-native-cli: 2.0.1`
`react-native: 0.55.4`

**expo version**
`"expo": "^27.0.1"`

**packages installed**
`"babel-plugin-react-native-classname-to-style": "^1.2.1"`
`"babel-plugin-react-native-platform-specific-extensions": "^1.1.1"`
`"node-sass": "^4.9.3"`
`"react-native-sass-transformer": "^1.2.2"`

**package.json**
`"expo": {
    "packagerOpts": {
      "sourceExts": [
        "js",
        "jsx",
        "scss",
        "sass"
      ],
      "transformer": "node_modules/react-native-sass-transformer/index.js"
    }
  },`

**.babelrc**
`{
  "presets": ["babel-preset-expo", "react-native"],
  "env": {
    "development": {
	  "plugins": ["transform-react-jsx-source", "react-native-classname-to-style",
		[
		  "react-native-platform-specific-extensions",
		  {
			"extensions": ["scss", "sass"]
		  }
		]
	  ]
    }
  }
}`

**index.js**
`import Styles from './index.scss';`
`<TextInput style={Styles.inputClass} />`

**index.scss**
`.inputClass {
	width: 100%
}`

**Comment by kristerkari** [comment] 2018-08-16 16:02
Thanks @wesleyamaro ! 

Hmm.. I wonder why that happens. Would it be possible for you upload your project somewhere where I could have a look at it?

At least the config looks correct to me.

**Comment by wesleyamaro** [comment] 2018-08-16 17:01
Hey @kristerkari 

Tks for replying back

You can look it at https://github.com/wesleyamaro/react-native-sass

Note: The command `import Styles` is commented

**Comment by kristerkari** [comment] 2018-08-16 19:30
@wesleyamaro I made a Pull Request that fixes your issue: https://github.com/wesleyamaro/react-native-sass/pull/1

**Comment by wesleyamaro** [comment] 2018-08-16 19:41
hmmmmm.... I'd seen ".json" and I thought it was package.json instead of app.json... 

Sorry my mistake... tks

**Comment by kristerkari** [comment] 2018-08-16 19:42
No worries! Let me know if you find something that does not work. 👍  I'll close this issue as it was solved.

**Closed by kristerkari** 2018-08-16 19:42 UTC

**Comment by wesleyamaro** [comment] 2018-08-17 22:11
@kristerkari 

I was trying using the extension .sass instead of .scss and I got failed build.

.sass has different syntax than .scss and the .sass file just work if I let the same syntax as .scss. Can you check it out please?

**Comment by wesleyamaro** [comment] 2018-08-20 13:51
No worries =)

I have found another point... Nesting css is not working too

https://sass-lang.com/guide

**Comment by kristerkari** [comment] 2018-08-22 18:42
@wesleyamaro 

> I was trying using the extension .sass instead of .scss and I got failed build.

I tested the indented Sass syntax, and it does not work because there was an option missing when calling the Sass compiler.

I have fixed it here, and I will release a new version of the Sass transformer soon:
https://github.com/kristerkari/react-native-sass-transformer/pull/11

> I have found another point... Nesting css is not working too

I don't know what exactly you are trying to nest, but React Native does not support nested selectors, so most of the Sass nesting won't work.

**Comment by wesleyamaro** [comment] 2018-08-23 00:45
@kristerkari 

Thank you! Let me know when you release the next version. 

About the "Nesting" I did not know about react-native support, no problem.

**Comment by kristerkari** [comment] 2018-08-23 05:57
The version 1.2.3 of the Sass transformer has the fix, please try it out :)

**Comment by wesleyamaro** [comment] 2018-08-24 21:48
Its working... cheers =)

**Comment by xsanda** [comment] 2019-07-09 11:40
I'm getting a very similar problem, with my MWE example [`xsanda/rn-css-modules-test`](/xsanda/rn-css-modules-test).

Error: `Unable to resolve "./Screen1.scss" from "app/screens/Screen1.tsx"`

**expo**: `33.0.7`

**package.json**: `"babel": { "presets": [ "babel-preset-expo" ], "plugins": [ "react-native-classname-to-style", [ "react-native-platform-specific-extensions", { "extensions": [ "scss" ] } ] ] },`

**app.json**: `"expo": { "packagerOpts": {."config": "metro.config.js", "sourceExts": ["js", "ts", "tsx"], "transformer": "node_modules/react-native-typed-sass-transformer/index.js" },`

**index.scss**:
```scss
.emptyComponentText {
  text-align: center;
}
```

**index.tsx**:
```ts
import React from "react";
import { View, Text } from "react-native";
import styles from "./index.scss";

// const styles = {};
export default () => (
  <View style={{ margin: 50 }}>
    <Text style={styles.emptyComponentText}>Blank text</Text>
  </View>
);
```

**Full error**:

```
Unable to resolve module `./index.scss` from `/Users/xsanda/Sites/rn-css-modules-test/app/index.tsx`: The module `./index.scss` could not be found from `/Users/xsanda/Sites/rn-css-modules-test/app/index.tsx`. Indeed, none of these files exist:
  * `/Users/xsanda/Sites/rn-css-modules-test/app/index.scss(.native||.ios.js|.native.js|.js|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.json|.native.json|.json)`
  * `/Users/xsanda/Sites/rn-css-modules-test/app/index.scss/index(.native||.ios.js|.native.js|.js|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.json|.native.json|.json)`
```

**Comment by kristerkari** [comment] 2019-07-09 11:45
@xsanda The configuration has changed for the newer Expo versions, I think that you are using the old format.

It should be like this:
https://github.com/kristerkari/react-native-sass-transformer#for-react-native-v057-or-newer--expo-sdk-v3100-or-newer

**Comment by kristerkari** [comment] 2019-07-09 11:53
@xsanda I can have a look at your example app later today to try to figure out what the issue is.

**Comment by xsanda** [comment] 2019-07-09 14:07
> @xsanda The configuration has changed for the newer Expo versions, I think that you are using the old format.
> 
> It should be like this:
> https://github.com/kristerkari/react-native-sass-transformer#for-react-native-v057-or-newer--expo-sdk-v3100-or-newer

Ah, you're right: I had combined both the old and the new form of the expo configuration, and with just the new form it is fixed. Thank you!

One more question, do you know if it is possible to use SCSS import paths relative to the root of the project? I would like to use variables from `app/config/globalStyles.scss` (or the platform-specific variant) in every SCSS file on my app, but it is hard to keep track of exactly how many directories to go up for each file if I use relative links.

**Comment by xsanda** [comment] 2019-07-09 14:11
@kristerkari Also, would you recommend that the `.scss.d.ts` files be committed or ignored?

**Comment by kristerkari** [comment] 2019-07-09 16:52
> One more question, do you know if it is possible to use SCSS import paths relative to the root of the project? I would like to use variables from `app/config/globalStyles.scss` (or the platform-specific variant) in every SCSS file on my app, but it is hard to keep track of exactly how many directories to go up for each file if I use relative links.

I think that that is not currently supported because it requires some extra config to Sass. I need to have a look at it and see if I can make it work. There is an open issue for it: https://github.com/kristerkari/react-native-sass-transformer/issues/19

> Also, would you recommend that the `.scss.d.ts` files be committed or ignored?

I would recommend to commit them. That way you can share the project with other people.
